export const SIGN_IN_REQUESTED = 'SIGN_IN_REQUESTED';
export const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const ADD_PATHWAY_REQUESTED = 'ADD_PATHWAY_REQUESTED';
export const ADD_PATHWAY_SUCCEEDED = 'ADD_PATHWAY_SUCCEEDED';
export const ADD_PATHWAY_FAILED = 'ADD_PATHWAY_FAILED';
