export const GET_FIDEL_TRANSACTIONS_REQUESTED = 'GET_FIDEL_TRANSACTIONS_REQUESTED';
export const GET_FIDEL_TRANSACTIONS_SUCCEEDED = 'GET_FIDEL_TRANSACTIONS_SUCCEEDED';
export const GET_FIDEL_TRANSACTIONS_FAILED = 'GET_FIDEL_TRANSACTIONS_FAILED';
export const GET_S_FIDEL_TRANSACTIONS_REQUESTED = 'GET_S_FIDEL_TRANSACTIONS_REQUESTED';
export const GET_S_FIDEL_TRANSACTIONS_SUCCEEDED = 'GET_S_FIDEL_TRANSACTIONS_SUCCEEDED';
export const GET_S_FIDEL_TRANSACTIONS_FAILED = 'GET_S_FIDEL_TRANSACTIONS_FAILED';
