export const GET_ETHEREUM_ADDRESS_REQUESTED = 'GET_ETHEREUM_ADDRESS_REQUESTED';
export const GET_ETHEREUM_ADDRESS_SUCCEEDED = 'GET_ETHEREUM_ADDRESS_SUCCEEDED';
export const GET_ETHEREUM_ADDRESS_FAILED = 'GET_ETHEREUM_ADDRESS_FAILED';

export const GET_ETHEREUM_NETWORK_REQUESTED = 'GET_ETHEREUM_NETWORK_REQUESTED';
export const GET_ETHEREUM_NETWORK_SUCCEEDED = 'GET_ETHEREUM_NETWORK_SUCCEEDED';
export const GET_ETHEREUM_NETWORK_FAILED = 'GET_ETHEREUM_NETWORK_FAILED';

export const CREATE_CONTRACT_INTERFACE = 'CREATE_CONTRACT_INTERFACE';
export const SET_CONTRACT_INTERFACE = 'SET_CONTRACT_INTERFACE';
