export const GET_WORKERS_REQUESTED = 'GET_WORKERS_REQUESTED';
export const GET_WORKERS_SUCCEEDED = 'GET_WORKERS_SUCCEEDED';
export const GET_WORKERS_FAILED = 'GET_WORKERS_FAILED';

export const REGISTER_WORKERS_REQUESTED = 'REGISTER_WORKERS_REQUESTED';
export const REGISTER_WORKERS_SUCCEEDED = 'REGISTER_WORKERS_SUCCEEDED';
export const REGISTER_WORKERS_FAILED = 'REGISTER_WORKERS_FAILED';
