export const GET_WORKERS_REQUESTED = 'GET_WORKERS_REQUESTED';
export const GET_WORKERS_SUCCEEDED = 'GET_WORKERS_SUCCEEDED';
export const GET_WORKERS_FAILED = 'GET_WORKERS_FAILED';

export const EDIT_WORKERS_REQUESTED = 'EDIT_WORKERS_REQUESTED';
export const EDIT_WORKERS_SUCCEEDED = 'EDIT_WORKERS_SUCCEEDED';
export const EDIT_WORKERS_FAILED = 'EDIT_WORKERS_FAILED';

export const REGISTER_WORKERS_REQUESTED = 'REGISTER_WORKERS_REQUESTED';
export const REGISTER_WORKERS_SUCCEEDED = 'REGISTER_WORKERS_SUCCEEDED';
export const REGISTER_WORKERS_FAILED = 'REGISTER_WORKERS_FAILED';

export const ADD_TRANSACTION_REQUESTED = 'ADD_TRANSACTION_REQUESTED';
export const ADD_TRANSACTION_SUCCEEDED = 'ADD_TRANSACTION_SUCCEEDED';
export const ADD_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED';

export const SEND_TOKENS_REQUESTED = 'SEND_TOKENS_REQUESTED';
export const SEND_TOKENS_SUCCEEDED = 'SEND_TOKENS_SUCCEEDED';
export const SEND_TOKENS_FAILED = 'SEND_TOKENS_FAILED';