export const SIGN_UP_COMPANY_REQUESTED = 'SIGN_UP_COMPANY_REQUESTED';
export const SIGN_UP_COMPANY_SUCCEEDED = 'SIGN_UP_COMPANY_SUCCEEDED';
export const SIGN_UP_COMPANY_FAILED = 'SIGN_UP_COMPANY_FAILED';
